trigger:
  - master

pr:
  - master

stages:
  - stage: build
    jobs:
    - job: 'BuildAndPublishArtifact'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: VSBuild@1
          displayName: 'Build solution ndevdb.sln'
          inputs:
            solution: '**\*.sln'