trigger:
  - master

pr:
  - master

stages:
  - stage: build
    jobs:
    - job: 'BuildAndPublishArtifact'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: VSBuild@1
          displayName: 'Build solution ndevdb.sln'
          inputs:
            solution: '**\*.sln'
        steps:
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/s'
            Contents: |
              **/*.dacpac
              **/*.publish.xml
            TargetFolder: '$(build.artifactstagingdirectory)/'
            CleanTargetFolder: true
            OverWrite: true
            flattenFolders: true
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(build.artifactstagingdirectory)'
            artifact: 'database-build'
            publishLocation: 'pipeline'