trigger:
  - master

pr:
  - master

resources:
  containers:
    - container: cidb
      image: mcr.microsoft.com/mssql/server:2019-latest
      env:
        ACCEPT_EULA: "Y"
        SA_PASSWORD: "Test2019.!"
      ports: 
      - 1433:1433

stages:
  - stage: build
    jobs:
    - job: 'BuildAndPublishArtifact'
      pool:
        vmImage: 'windows-latest'
      steps:
        - task: VSBuild@1
          displayName: 'Build solution ndevdb.sln'
          inputs:
            solution: '**\*.sln'
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Pipeline.Workspace)/s'
            Contents: |
              **/*.dacpac
              **/*.publish.xml
            TargetFolder: '$(build.artifactstagingdirectory)/'
            CleanTargetFolder: true
            OverWrite: true
            flattenFolders: true
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(build.artifactstagingdirectory)'
            artifact: 'database-build'
            publishLocation: 'pipeline'
  
  - stage: test
    dependsOn: build
    jobs:
    - job: 'RunUnitTests'
      services:
        cidb : cidb
      pool:
        vmImage: 'ubuntu-18.04'
      steps:
        - script: |
            mkdir sqlpackage
            cd ./sqlpackage
            wget https://download.microsoft.com/download/d/e/b/deb7b081-a3dc-47ea-8f2a-48cd8e486036/sqlpackage-linux-x64-en-US-15.0.4630.1.zip
            ls -a
